AWSTemplateFormatVersion: 2010-09-09
Description: This is Instance is with Tomcat

Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Docker SecrityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22' 
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
  
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0eb260c4d5475b901
      InstanceType: t2.micro
      KeyName: PKUK
      SecurityGroups:
        - !Ref JenkinsSecurityGroup
      Tags:
        - Key: Name
          Value: JenkinsInstance